--Câu 16:
SELECT MASP,TENSP 
FROM SANPHAM 
WHERE MASP NOT IN( SELECT CTHD.MASP FROM HOADON ,CTHD WHERE YEAR(HOADON.NGHD)=2006 AND CTHD.SOHD= HOADON.SOHD)


--Câu 17:
SELECT MASP,TENSP 
FROM SANPHAM 
WHERE NUOCSX='TRUNG QUOC' 
AND MASP NOT IN( SELECT CTHD.MASP FROM CTHD,HOADON WHERE CTHD.SOHD=HOADON.
SOHD AND YEAR(HOADON.NGHD)=2006)


--Câu 18:
SELECT H.SOHD 
FROM HOADON H
WHERE NOT EXISTS(SELECT *
FROM SANPHAM S
WHERE NUOCSX = 'SINGAPORE'
AND NOT EXISTS(SELECT * 
FROM CTHD C
WHERE C.SOHD = H.SOHD
AND C.MASP = S.MASP))
SELECT DISTINCT CT.SOHD 
FROM CTHD CT
WHERE NOT EXISTS(SELECT *
FROM SANPHAM S
WHERE NUOCSX = 'SINGAPORE'
AND NOT EXISTS(SELECT * 
FROM CTHD C
WHERE C.SOHD = CT.SOHD
AND C.MASP = S.MASP))



--Câu 19:
SELECT H.SOHD 
FROM HOADON H
WHERE YEAR(NGHD) = 2006 AND NOT EXISTS(SELECT *
FROM SANPHAM S
WHERE NUOCSX = 'SINGAPORE'
AND NOT EXISTS(SELECT * 
FROM CTHD C
WHERE C.SOHD = H.SOHD
AND C.MASP = S.MASP))



--Câu 20:
SELECT COUNT(HOADON.MAKH ) 
AS "SO KHACH HANG KHONG DANG KY MA MUA" 
FROM HOADON 
WHERE HOADON.MAKH NOT IN( SELECT MAKH FROM KHACHHANG WHERE KHACHHANG.MAKH=HOADON.MAKH)


--Câu 21:
SELECT COUNT(CTHD.MASP)
AS "SO LUONG SAN PHAM KHAC NHAU " 
FROM CTHD,HOADON 
WHERE CTHD.SOHD=HOADON.SOHD AND YEAR(HOADON.NGHD)=2006

--Câu22:
SELECT MAX(TRIGIA)AS "TRI GIA CAO NHAT", MIN(TRIGIA) AS "TRI GIA THAP NHAT LA " 
FROM HOADON


--Câu 23:
SELECT AVG(TRIGIA)AS "TRUNG BINH CUA TAT CA CAC HOA DON 2006" 
FROM HOADON 
WHERE YEAR(NGHD)=2006


--Câu 24:
SELECT SUM(TRIGIA) AS "DOANH THU CUA HANG" 
FROM HOADON 
WHERE NGHD=2006


--Câu 25:
SELECT SOHD 
FROM HOADON 
WHERE YEAR(NGHD)=2006 AND TRIGIA=(SELECT MAX(TRIGIA) FROM HOADON)


--Câu 26:
SELECT KHACHHANG.HOTEN 
FROM KHACHHANG ,HOADON 
WHERE YEAR(NGHD)=2006 AND TRIGIA=(SELECT MAX(TRIGIA) FROM HOADON ) 
AND HOADON.MAKH=KHACHHANG.MAKH


--Câu 27:
SELECT TOP 3 MAKH,HOTEN 
FROM KHACHHANG 
ORDER BY DOANHSO DESC


--Câu 28:
SELECT MASP,TENSP 
FROM SANPHAM 
WHERE GIA IN (SELECT TOP 3 GIA FROM SANPHAM ORDER BY GIA DESC)


--Câu 29:
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'THAI LAN' AND GIA IN (SELECT DISTINCT TOP 3 GIA
FROM SANPHAM
ORDER BY GIA DESC)


--Câu 30:
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC' AND GIA IN (SELECT DISTINCT TOP 3 GIA
FROM SANPHAM
ORDER BY GIA DESC)


--Câu 31:
SELECT TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC


--Câu 32:
SELECT COUNT(DISTINCT MASP)
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'


--Câu 33:
SELECT NUOCSX, COUNT(DISTINCT MASP) AS TONGSOSANPHAM
FROM SANPHAM
GROUP BY NUOCSX


--Câu 34:
SELECT NUOCSX, MAX(GIA) AS MAX, MIN(GIA) AS MIN, AVG(GIA) AS AVG
FROM SANPHAM
GROUP BY NUOCSX


--Câu 35:
SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD

