select * from NHANVIEN 
--1.
select NHANVIEN.HONV, NHANVIEN.TENLOT,NHANVIEN.TENNV
from NHANVIEN
where PHG = 4
--2.
select NHANVIEN.HONV, NHANVIEN.TENLOT,NHANVIEN.TENNV,NHANVIEN.LUONG
from NHANVIEN
where LUONG > 30000
--3.
select NHANVIEN.HONV, NHANVIEN.TENLOT,NHANVIEN.TENNV,NHANVIEN.LUONG
from NHANVIEN
where (LUONG > 25000 and PHG = 4) or (LUONG > 30000 and PHG = 5)
--4.
select NHANVIEN.HONV, NHANVIEN.TENLOT,NHANVIEN.TENNV
from NHANVIEN
where DCHI like '%hcm%'
--5.
select NHANVIEN.HONV, NHANVIEN.TENLOT,NHANVIEN.TENNV
from NHANVIEN
where HONV like 'N%'
--6.
select NHANVIEN.NGSINH, NHANVIEN.DCHI
from NHANVIEN
where HONV = N'Đinh' and TENLOT = N'Bá' and TENNV = N'Tiên'